---
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: 0 0 * * 1

permissions:
  contents: read
  pull-requests: read

jobs:
  golang-checks:
    name: Golang checks
    uses: bodgit/workflows/.github/workflows/golang-checks.yml@90676a57fa5e7bb53dbea051211751b225ee60ca # v1.0.1
