---
name: Track releases

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    name: Run release-please
    uses: bodgit/workflows/.github/workflows/release.yml@90676a57fa5e7bb53dbea051211751b225ee60ca # v1.0.1
    secrets:
      RELEASE_PLEASE_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
