---
name: Track releases

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    name: Run release-please
    uses: bodgit/workflows/.github/workflows/release.yml@dd43086767b331dc0010100dd2a304663999f80a # v1.0.2
    secrets:
      RELEASE_PLEASE_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
